# Generated by Django 5.2.7 on 2025-10-20 09:23

import cloudinary.models
import django.utils.timezone
import django_summernote.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.PositiveIntegerField()),
                ('unit', models.CharField(choices=[('Kg', 'Kg'), ('Gm', 'Gm'), ('Pcs', 'Pcs'), ('Dozen', 'Dozen')], default='Kg')),
                ('is_active', models.BooleanField(default=False)),
                ('description', django_summernote.fields.SummernoteTextField(blank=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ManyToManyField(to='product.category')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
