# Generated by Django 5.2.7 on 2025-10-21 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='point',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
