# Generated by Django 5.2.7 on 2025-10-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productreview_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='point',
            field=models.PositiveIntegerField(choices=[(0, 'Bad'), (1, 'Good'), (2, 'Satisfied'), (3, 'Best')], default=3),
        ),
    ]
