# Generated by Django 5.2.7 on 2025-10-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
