# Generated by Django 5.2.7 on 2025-10-25 06:22

import cloudinary.models
import django.utils.timezone
import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(help_text="If you've multiple phone number , separate them via comma(,)", max_length=110)),
                ('location', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('terms_and_conditions', django_summernote.fields.SummernoteTextField(blank=True)),
                ('established_at', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
