# Generated by Django 5.2.7 on 2025-10-25 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutshop',
            options={'ordering': ['-created_at'], 'verbose_name': 'Shop Info', 'verbose_name_plural': 'Shop Info'},
        ),
    ]
