# Generated by Django 5.2.7 on 2025-10-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_type', models.CharField(choices=[('Inside', 'Inside'), ('Outside', 'Outside')], max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('charge', models.PositiveIntegerField()),
            ],
        ),
    ]
