# Generated by Django 5.2.7 on 2025-10-25 12:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cartitem_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('location', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Pending', 'Pending'), ('Placed', 'Placed'), ('Cancled', 'Cancled')], default='Pending', max_length=30)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.cart')),
                ('items', models.ManyToManyField(to='cart.cartitem')),
            ],
            options={
                'verbose_name': 'Confirmed Order',
                'verbose_name_plural': 'Confirmed Orders',
                'ordering': ['-date'],
            },
        ),
    ]
