# Generated by Django 5.2.7 on 2025-10-25 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_shippingcharge'),
        ('cart', '0007_confirmorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmorder',
            name='shipping_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='about.shippingcharge'),
        ),
    ]
